Update jenkinsfile_khoubaib

diff --git a/jenkinsfile_khoubaib b/jenkinsfile_khoubaib
--- a/jenkinsfile_khoubaib
+++ b/jenkinsfile_khoubaib
@@ -1,49 +1,105 @@
-pipeline{
+pipeline {
+    agent any
 
-      agent any
-        tools {
-     jdk 'JAVA_HOME'
-     maven 'M2_HOME'
-  }
-     
-        
-        stages{
+    tools {
+        maven 'M2_HOME'
+        jdk 'JAVA_HOME'
+    }
+    environment {
+        NEXUS_VERSION = "nexus3"
+        NEXUS_PROTOCOL = "http"
+        NEXUS_URL = "0.0.0.0:8081"
+        NEXUS_REPOSITORY = "maven-nexus-repo"
+        NEXUS_CREDENTIAL_ID = "nexus-user-credentials"
+        registry = "ahmedazizelj/achat_back"
+        registryCredential = 'ahmedazizelj'
+        dockerImage = ''
+    }
 
+    stages {
+        stage('Getting project from Github') {
+            steps {
+                git branch : 'fournisseur' ,
+                    url : 'https://github.com/ahmedaziz-code/app-achat.git';
+            }
+        }
+        stage('database connection') {
+            steps{
+                sh '''
+                sudo docker stop mysql || true
+                sudo docker restart mysql || true
+                '''
+            }
+        }
+        stage('cleanig the project') {
+            steps{
+                sh 'mvn clean'
+            }
 
-                            stage('Testing process') {
-                              steps {
-                               script {
-                                sh 'echo "Test is processing ...."'
-                                sh 'mvn clean test'
-                               }
-
-                              }
-
-                            }
-
-               stage('Quality Gate Status Check'){
-                  steps{
-                      script{
-			      withSonarQubeEnv('sonar') {
-			      sh "mvn compile sonar:sonar"
-                       	     	}
-			      timeout(time: 1, unit: 'HOURS') {
-			      def qg = waitForQualityGate()
-				      if (qg.status != 'OK') {
-					   error "Pipeline aborted due to quality gate failure: ${qg.status}"
-				      }
-                    		}
-		    	    sh "mvn clean install"
-
-                 	}
-               	 }
-              }
-		stage("Maven Build") {
+        }
+        stage ('artifact construction') {
+            steps{
+                sh 'mvn  package'
+            }
+        }
+        stage ('Unit Test') {
+            steps{
+                sh 'mvn  test'
+            }
+        }
+        stage ('SonarQube analysis') {
+            steps{
+                sh '''
+                mvn sonar:sonar
+                '''
+            }
+        }
+        stage("Publish to Nexus Repository Manager") {
             steps {
                 script {
-                    sh 'sudo docker build --build-arg IP=0.0.0.0 -t ahmedazizelj/achat_back .'
+                    pom = readMavenPom file: "pom.xml";
+                    filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
+                    echo "${filesByGlob[0].name} ${filesByGlob[0].path} ${filesByGlob[0].directory} ${filesByGlob[0].length} ${filesByGlob[0].lastModified}"
+                    artifactPath = filesByGlob[0].path;
+                    artifactExists = fileExists artifactPath;
+                    if(artifactExists) {
+                        echo "*** File: ${artifactPath}, group: ${pom.groupId}, packaging: ${pom.packaging}, version ${pom.version}";
+                        nexusArtifactUploader(
+                            nexusVersion: NEXUS_VERSION,
+                            protocol: NEXUS_PROTOCOL,
+                            nexusUrl: NEXUS_URL,
+                            groupId: pom.groupId,
+                            version: pom.version,
+                            repository: NEXUS_REPOSITORY,
+                            credentialsId: NEXUS_CREDENTIAL_ID,
+                            artifacts: [
+                                [artifactId: pom.artifactId,
+                                classifier: '',
+                                file: artifactPath,
+                                type: pom.packaging],
+                                [artifactId: pom.artifactId,
+                                classifier: '',
+                                file: "pom.xml",
+                                type: "pom"]
+                            ]
+                        );
+                    } else {
+                        error "*** File: ${artifactPath}, could not be found";
+                    }
                 }
             }
         }
+        stage ('Build our image'){
+            steps{
+                sh 'sudo docker build --build-arg IP=0.0.0.0 -t ahmedazizelj/achat_back .'
+            }
         }
+        stage ('Deploy our image'){
+            steps{
+                sh 'sudo docker login -u ahmedazizelj -p azizaziz1';
+                sh 'sudo docker push ahmedazizelj/achat_back'
+                }
+            }
+
+    }
 }
